hello world:
  script: echo "Hello world"

build:
  image: rootproject/root-conda:6.18.04
  script:
    - COMPILER=$(root-config --cxx)
    - FLAGS=$(root-config --cflags --libs)
    #- MY_CMTCONFIG=x86_64-slc6-gcc49-opt
    #- source /cvmfs/lhcb.cern.ch/lib/LbEnv.sh -c ${MY_CMTCONFIG}
    #- MYROOTPATH=/cvmfs/lhcb.cern.ch/lib/lcg/releases/LCG_76root6/ROOT/6.02.08/x86_64-slc6-gcc49-opt
    #- $COMPILER -g -std=c++11 -O2  -pthread -m64 -Wall -Wextra -Wpedantic -I${MYROOTPATH}/include ${CODE_INPUT}/*.cpp -o HBTAnalysis -L${MYROOTPATH}/lib -lGpad -lHist -lGraf -lGraf3d -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lRIO -lNet -lThread -lCore  -pthread -lm -ldl -rdynamic -lTreePlayer -lMinuit -lTMVA -lXMLIO -lMLP
    - CODE_INPUT=code/HBTAnalysis
    - $COMPILER -g -O3 -Wall -Wextra -Wpedantic ${CODE_INPUT}/*.cpp -o HBTAnalysis $FLAGS
    
build_latest:
  image: rootproject/root-conda:latest
  script:
    - COMPILER=$(root-config --cxx)
    - FLAGS=$(root-config --cflags --libs)
    #- MY_CMTCONFIG=x86_64-slc6-gcc49-opt
    #- source /cvmfs/lhcb.cern.ch/lib/LbEnv.sh -c ${MY_CMTCONFIG}
    #- MYROOTPATH=/cvmfs/lhcb.cern.ch/lib/lcg/releases/LCG_76root6/ROOT/6.02.08/x86_64-slc6-gcc49-opt
    #- $COMPILER -g -std=c++11 -O2  -pthread -m64 -Wall -Wextra -Wpedantic -I${MYROOTPATH}/include ${CODE_INPUT}/*.cpp -o HBTAnalysis -L${MYROOTPATH}/lib -lGpad -lHist -lGraf -lGraf3d -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lRIO -lNet -lThread -lCore  -pthread -lm -ldl -rdynamic -lTreePlayer -lMinuit -lTMVA -lXMLIO -lMLP
    - CODE_INPUT=code/HBTAnalysis
    - $COMPILER -g -O3 -Wall -Wextra -Wpedantic ${CODE_INPUT}/*.cpp -o HBTAnalysis $FLAGS
  allow_failure: true


