stages:
  - greeting
  - build

hello world:
  stage: greeting
  script: echo "Hello world"

.build_template:
  stage: build
  before_script:
    - COMPILER=$(root-config --cxx)
    - FLAGS=$(root-config --cflags --libs)
    - CODE_INPUT=code/HBTAnalysis
  script:
    - $COMPILER -g -O3 -Wall -Wextra -Wpedantic ${CODE_INPUT}/*.cpp -o HBTAnalysis $FLAGS
  only:
    changes:
      - ${CODE_INPUT}/*.cpp

build_stable:
  extends: .build_template
  image: rootproject/root-conda:6.18.04
  
    
build_latest:
  extends: .build_template
  image: rootproject/root-conda:latest
  allow_failure: true
  