#!/bin/sh

build_tool=cmake

if [ -z "$CMTCONFIG" ] ; then
  echo "error: CMTCONFIG not defined"
  exit 1
fi

if [ "cmake" = "cmake" ] ; then
  run_cmd=$(dirname $0)/build.$CMTCONFIG/run
  if [ -e "$run_cmd" ] ; then
    exec $run_cmd "$@"
  else
    echo "error: cannot find build.$CMTCONFIG/run, did you build?"
    exit 1
  fi
else
  curdir=$(pwd)
  cd $(dirname $0)
  . ./build_env.sh
  cd $curdir
  . SetupProject.sh --keep-CMTPROJECTPATH --user $(cd $(dirname $0)/.. ; pwd) UraniaDev_v7r0
  if [ "$SetupProjectStatus" = 0 ] ; then
    [ "$#" = 0 ] && (printenv | sort) || exec "$@"
  else
    exit $SetupProjectStatus
  fi
fi
